include:
- ./functions/mastodonharvester2.py
kind: ArchiveUploadSpec
name: functions-mastodonharvester2-py-Xyka

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: mastodonharvester2-a2b6125d-9cfd-4a4f-a3c6-401893fb504c
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://functions-mastodonharvester2-py-Xyka
  environment:
    name: python3
    namespace: ""
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2024-05-21T20:44:15Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: mastodonharvester2
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  configmaps:
  - name: configmap-mastodon
    namespace: ""
  environment:
    name: python3
    namespace: ""
  functionTimeout: 300
  idletimeout: 120
  package:
    packageref:
      name: mastodonharvester2-a2b6125d-9cfd-4a4f-a3c6-401893fb504c
      namespace: ""
  requestsPerPod: 1
  resources: {}
