include:
- ./functions/search.py
kind: ArchiveUploadSpec
name: functions-search-py-ybwj

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: search-6704a99b-bc2f-4354-9b47-a5ffea8fc8a1
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://functions-search-py-ybwj
  environment:
    name: python3
    namespace: ""
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2024-05-21T20:44:52Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: search
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  configmaps:
  - name: configmap-es
    namespace: ""
  environment:
    name: python3
    namespace: ""
  functionTimeout: 300
  idletimeout: 120
  package:
    packageref:
      name: search-6704a99b-bc2f-4354-9b47-a5ffea8fc8a1
      namespace: ""
  requestsPerPod: 1
  resources: {}
