include:
- ./functions/addobservations.py
kind: ArchiveUploadSpec
name: functions-addobservations-py-WnpQ

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: addobservations-482cd80a-aae1-47e1-8d2b-039a67b15c65
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://functions-addobservations-py-WnpQ
  environment:
    name: python3
    namespace: ""
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2024-05-21T20:42:56Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: addobservations
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  configmaps:
  - name: configmap-es
    namespace: ""
  environment:
    name: python3
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: addobservations-482cd80a-aae1-47e1-8d2b-039a67b15c65
      namespace: ""
  requestsPerPod: 1
  resources: {}
