include:
- ./functions/incomeprocessor.py
kind: ArchiveUploadSpec
name: functions-incomeprocessor-py-qizG

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: incomeprocessor-19620bfb-de1f-42e2-ad7c-3603bf0a5ff4
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://functions-incomeprocessor-py-qizG
  environment:
    name: python3
    namespace: ""
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2024-05-21T20:43:35Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: incomeprocessor
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: python3
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: incomeprocessor-19620bfb-de1f-42e2-ad7c-3603bf0a5ff4
      namespace: ""
  requestsPerPod: 1
  resources: {}
