include:
- ./functions/twitterprocessor.py
kind: ArchiveUploadSpec
name: functions-twitterprocessor-py-Vd9P

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: twitterprocessor-4bda5d2f-5501-44cf-8d65-a59d86f33d11
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://functions-twitterprocessor-py-Vd9P
  environment:
    name: python3
    namespace: ""
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2024-05-21T20:45:13Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: twitterprocessor
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: python3
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: twitterprocessor-4bda5d2f-5501-44cf-8d65-a59d86f33d11
      namespace: ""
  requestsPerPod: 1
  resources: {}
