apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: search-get1
spec:
  createingress: true
  functionref:
    functionweights: null
    name: search
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /search/{server:[a-zA-Z0-9]+}/keyword/{keyword:[a-zA-Z0-9]+}
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /search/{server:[a-zA-Z0-9]+}/keyword/{keyword:[a-zA-Z0-9]+}
